"""
PipeIQ Framework - Phantom Wallet Integration
"""

from .phantom import (
    PhantomWallet,
    NetworkType,
    TransactionStatus,
    SwapType,
    NFTStandard,
    StakeType,
    ProgramType,
    WalletFeature,
    WalletConfig,
    TransactionConfig,
    SwapConfig,
    NFTConfig,
    StakeConfig,
    ProgramConfig,
    WalletFeatureConfig,
    PhantomError,
    ConnectionError,
    TransactionError,
    SwapError,
    NFTError,
    StakeError,
    ProgramError,
    FeatureError,
)

__version__ = "0.1.0"
__all__ = [
    "PhantomWallet",
    "NetworkType",
    "TransactionStatus",
    "SwapType",
    "NFTStandard",
    "StakeType",
    "ProgramType",
    "WalletFeature",
    "WalletConfig",
    "TransactionConfig",
    "SwapConfig",
    "NFTConfig",
    "StakeConfig",
    "ProgramConfig",
    "WalletFeatureConfig",
    "PhantomError",
    "ConnectionError",
    "TransactionError",
    "SwapError",
    "NFTError",
    "StakeError",
    "ProgramError",
    "FeatureError",
]
